spring:
    datasource:
        url: jdbc:h2:mem:books;DB_CLOSE_DELAY=-1

    h2:
        console:
            path: /h2-console
            settings:
                web-allow-others: true
            enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        show-sql: true