spring:
  data:
    mongodb:
#      uri: mongodb://localhost
      database: library
#      host: my-host-mongodb
      port: 27017
#  profiles:
#    active: prod

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - mongodb.changelog


#hystrixdashboard  ---> localhost:8080/hystrix ----> http://localhost:8080/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

hystrix:
  dashboard:
    proxy-stream-allow-list:
      - 'localhost'
